#include<stdio.h>
#include<conio.h>


void main(){

clrscr();
	gotoxy(10,2);printf("Aммм");
	gotoxy(10,3);printf("ALAS-");
	gotoxy(10,4);printf("KA");
	gotoxy(15,1);printf("зддддддд©                   здддддддддбдддддд©мммA ARAL");
	gotoxy(15,2);printf("╣ISLANDIA                   Ё SUECIA  Ё      юддд©");
	gotoxy(15,3);printf("Ё       фммммммммммммммммммм╣         Ё RUSIA    юдд©ммA IRAN");
	gotoxy(15,4);printf("юдддрддды                   юдддддддддад©           юд©");
	gotoxy(15,5);printf("    ╨                                   Ё             ю©мA TUR-");
	gotoxy(15,6);printf("    ╨                                   цддддд©        ю©  QUIA");
	gotoxy(15,7);printf("    ╨           зддд©                   Ё     юддддд©   ю©");
	gotoxy(15,8);printf("    ╨          зы   Ё                   Ё           юддддадд©");
	gotoxy(15,9);printf("    ╨         зыGRANЁ                  зы  POLONIA          Ё");
	gotoxy(15,10);printf("    хммммммммм╣BRE- Ё                 заддддддддд©          фмммA");
	gotoxy(15,11);printf("              ЁTA╔A фммммммммммммммямм╬          юдддд©   здыEGIP-");
	gotoxy(15,12);printf("              юддрдды         зддбды                  юдбды   TO");
	gotoxy(15,13);printf("                 ╨       здддды  юдддд©  ALEMANIA    здды");
	gotoxy(15,14);printf("                 ╨     зды            юдддд©      здды");
	gotoxy(15,15);printf("                 ╨ здбды                   юдд©   Ё");
	gotoxy(15,16);printf("           здддддпды Ё      FRANCIA         здаддд╢");
	gotoxy(15,17);printf("           Ё         юдд©             зддддда©ITA-ю©");
	gotoxy(15,18);printf("           Ё  ESPA╔A   заддддддддддддды      ЁLIA  Ё");
	gotoxy(15,19);printf("           юдддддддддды                     Ё     Ё");
	gotoxy(15,20);printf("              A SAHARA                       юддддды");


getch();
}
