#include<stdio.h>
#include<conio.h>


void main(){

clrscr();
	   gotoxy (18,1);printf("A MALASIA");
	   gotoxy (21,2);printf("");
	   gotoxy (20,3);printf("зд©");
	   gotoxy (20,4);printf("ЁBORNEO");
	   gotoxy (20,5);printf("Ё Ё");
	   gotoxy (20,6);printf("Ё Ё");
	   gotoxy (20,7);printf("юры");
	   gotoxy (21,8);printf("╨");
	   gotoxy (21,9);printf("╨");

	   gotoxy (11,2);printf("A INDIA");
	   gotoxy (14,3);printf("");
	   gotoxy (14,4);printf("╨");
	   gotoxy (14,5);printf("╨");
	   gotoxy (13,6);printf("зп©");
	   gotoxy (13,7);printf("Ё Ё");
	   gotoxy (13,8);printf("ЁSUMATRA");
	   gotoxy (13,9);printf("юры");
	   gotoxy (14,10);printf("╨");
	   gotoxy (14,11);printf("хмм");




	   gotoxy (25,5);printf("зд©");
	   gotoxy (25,6);printf("Ё Ё");
	   gotoxy (25,7);printf("ЁJAVA");
	   gotoxy (25,8);printf("юры");
	   gotoxy (26,9);printf("╨");





	   gotoxy (17,10);printf("здддпддддпддддд© ");
	   gotoxy (17,11);printf("╣              Ё  ");
	   gotoxy (17,12);printf("Ё AUSTRALIA    фммммммммм");
	   gotoxy (17,13);printf("ю©            зы ");
	   gotoxy (17,14);printf(" юдддддддддддды");

	gotoxy (37,2);printf(" A MEXICO");
	gotoxy (37,3);printf("                        имммммммммA SAHARA");
	gotoxy (37,4);printf("зддддпддддд© здддддддддддп©");
	gotoxy (37,5);printf("юд©COLOMBIAцды           зы");
	gotoxy (37,6);printf("  ю©       Ё  BRASIL    зы");
	   gotoxy (40,7);printf("цддддддд╢           зы");
	   gotoxy (40,8);printf("Ё PERU  Ё          зы");
	   gotoxy (40,9);printf("цддбддддабддддддддд╢");
	   gotoxy (40,10);printf("Ё CЁ     ю©URUGUAY Ё");
	   gotoxy (40,11);printf("ю©HЁ      ю©      зы");
	   gotoxy (40,12);printf("м╣IЁ       юдд©  зы ");
	   gotoxy (40,13);printf(" ЁLЁ          юдбы");
	   gotoxy (40,14);printf(" ЁEЁARGENTINA  зы");
	   gotoxy (40,15);printf(" Ё Ё          зы");
	   gotoxy (40,16);printf(" ю©ю©        зы");
	   gotoxy (40,17);printf("  ю©ю©      зы");
	   gotoxy (40,18);printf("   юбы    зды");
	   gotoxy (40,19);printf("    Ё   зды");
	   gotoxy (40,20);printf("    юддды");


getch();
}
